/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Bellie(props) {
  const { nodes, materials } = useGLTF("/bellie.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve005.geometry}
        material={materials["SVGMat.004"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve005_1.geometry}
        material={materials["SVGMat.005"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve005_2.geometry}
        material={materials["SVGMat.006"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve005_3.geometry}
        material={materials["SVGMat.007"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve005_4.geometry}
        material={materials["SVGMat.008"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve005_5.geometry}
        material={materials["SVGMat.009"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve005_6.geometry}
        material={materials["SVGMat.010"]}
      />
    </group>
  );
}

useGLTF.preload("/bellie.glb");
